7 module complete
alexander-shvetsov/skillboxHomeWorks pull request #5
Opened 2020-09-23 10:27 UTC by alexander-shvetsov

2020-09-24 07:37 UTC, ios-review requested changes
Упс.

Не нажали submit review)

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Background.swift
> +func getBackground(from buttonName: String) -> UIColor {
global func?

Будет ок только, если используется в сугубо технических целях, вроде log.

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Background.swift
> +enum Background: String {
Сделать функцию вычисления UIColor в качестве функции-члена данного перечисления.

Затем создавать перечисление по rawValue и преобразовывать в UIColor.

```
enum Background: String {
    case green
    
    var color: UIColor {
          return .green
    }
}
```

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ColorViewController.swift
> +class ColorViewController: UIViewController {
Ошибка лейаута для кнопки изменить.
На SE (2nd)

<img width="389" alt="Screenshot 2020-09-24 at 12 39 27" src="https://user-images.githubusercontent.com/62285448/94105290-2984ae00-fe63-11ea-82c7-34194da66a0c.png">

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/BackgroundViewController.swift
> +        guard let isPressedButton = sender.currentTitle else { return }
currentTitle - не надежный идентификатор.
Title - это контент для пользователя.

Он может быть изменен в любое время другим разработчиком по просьбе контент-менеджера или аналитика.
Причин его изменения очень много.

В качестве идентификатора рекомендую использовать tag.
https://developer.apple.com/documentation/uikit/uiview/1622493-tag
tag можно задать в сториборде.

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/BackgroundViewController.swift
> +который обязует контроллер, принимать новое значение фона */
Комментарии - топ😍

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +    @IBAction func buttonPressed(_ sender: UIButton) {
Предлагаю поисследовать вопрос: "Как именовать @IBAction функции?"

После исследования написать краткое резюме + ссылки, которые были изучены.
Ответ написать к этому комментарию.

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +        dismiss(animated: true, completion: nil) // close
`dismiss(animated: true)`

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +        dismiss(animated: true, completion: nil) // close
если что-то можно не делать, лучше этого не делать)

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ColorViewController.swift
> +        changeColorVC.settedColor = titleLabel.text!
force unwrap

2020-09-24 07:37 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +enum Colors: String {
Две по сути очень близких модели в одном приложении, которое все про цвет.

Может воспользоваться одной моделью?
И добавить еще одно вычисляемое свойство для текстового описания цвета.

2020-09-29 05:25 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Model/Background.swift
> +enum Background: String {
Реализовал общую модель для работы с цветом: как текстовой части, так и фона.

2020-09-29 05:26 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Controllers/ColorViewController.swift
> +class ColorViewController: UIViewController {
Так точно, не углядел. Кое-где произвёл рефакторинг UI

2020-09-29 05:26 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Controllers/BackgroundViewController.swift
> +        guard let isPressedButton = sender.currentTitle else { return }
Вот это да, совсем не подумал о пользовательской части. Действительно использовать tag гораздо выгоднее. Скорее всего для модели калькулятора этот подход и буду использовать.

2020-09-29 05:34 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +    @IBAction func buttonPressed(_ sender: UIButton) {
Материалы:
https://swift.org/documentation/api-design-guidelines/#naming
https://medium.com/better-programming/naming-conventions-in-swift-4b7ca5eed4d2
Кое-что было написано в книгах...
===
That's my fail 😕
Всегда старался именовать всё отвечая на вопросы: что, для чего, что будет и т.д., а здесь почему-то отнёсся к кнопке чисто технически, по моему где-то увидел у кого-то такое именование, и "прилипло"... Моя ошибка.
Где-то читал, что код swift прекрасен как раз тем, что зная английский язык, в идеале, можно читать как рассказ. К этому стоит стремиться наверное ☺️

2020-09-29 05:34 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +        dismiss(animated: true, completion: nil) // close
А что, так можно было чтоли? (с)
😁
Так точно, буду знать. Благодарю!

2020-09-29 05:35 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Controllers/ColorViewController.swift
> +        changeColorVC.settedColor = titleLabel.text!
Виноват, исправился.

2020-09-29 05:35 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +enum Colors: String {
Так точно, реализовал одну общую модель для работы с цветом.

2020-10-01 10:18 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Controllers/ChangeColorViewController.swift
> +    @IBAction func buttonPressed(_ sender: UIButton) {
👍

2020-10-01 10:20 UTC, ios-review requested changes
Стало очень круто!

Упростите реализацию свойств перечисления Colors?

2020-10-01 10:20 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +enum Colors: Int {
Мне кажется, с данным перечислением все стало гораздо круче)
Что вы думаете?

2020-10-01 10:20 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +        switch self.rawValue {
если делать switch по self без rawValue, то тогда можно будет не указывать default блок.

2020-10-01 10:20 UTC, ios-review commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +        switch self.rawValue {
если делать switch по self без rawValue, то тогда можно будет не указывать default блок.

2020-10-02 03:17 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +enum Colors: Int {
Однозначно!

2020-10-02 03:18 UTC, alexander-shvetsov commented on 7 module/7.7 Tab Bar Controller/Model/Colors.swift
> +enum Colors: Int {
Только почему-то в review отображён пример старого кода 🤔

2020-10-04 06:57 UTC, ios-review approved these changes
Все очень круто! Идеально!
Коротко, лакончино, с комментариями!
Молодец🔥

Мрежим.

2020-10-04 06:59 UTC, merged